steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/analytical-poet-439812-s7/gcp-demo-repo/gcp-demo-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/analytical-poet-439812-s7/gcp-demo-repo/gcp-demo-app']
images:
- 'asia-south1-docker.pkg.dev/analytical-poet-439812-s7/gcp-demo-repo/gcp-demo-app'
options:
  logging: CLOUD_LOGGING_ONLY
  #peep
